import { AppProvider } from "@/shared/providers/app-provider";
import { Toaster } from "@/shared/ui/sonner";
import type { Metadata } from "next";
import { sfProText } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${sfProText.className} antialiased min-h-svh`}>
        <AppProvider>
          {children}
          <Toaster />
        </AppProvider>
      </body>
    </html>
  );
}
