import { catalogControllerGetCurrent } from "@/shared/api/generated";
import { AppProvider } from "@/shared/providers/app-provider";
import { Toaster } from "@/shared/ui/sonner";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { sfProText } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await catalogControllerGetCurrent();

  const {
    name,
    config: { about, description },
  } = data ?? {};

  if (!data) {
    notFound();
  }

  return (
    <html lang="ru">
      <body className={`${sfProText.className} antialiased min-h-svh`}>
        <AppProvider initialCatalog={data}>{children}</AppProvider>
        <Toaster />
      </body>
    </html>
  );
}
